#!/bin/bash
# SVN Upload Steps for Enhanced Autoload Manager
# Make sure you've set up your SVN password first!

echo "Enhanced Autoload Manager - SVN Upload Steps"
echo "==========================================="
echo ""
echo "1. First, check out the SVN repository:"
echo "   svn checkout https://plugins.svn.wordpress.org/enhanced-autoload-manager enhanced-autoload-manager-svn"
echo ""
echo "2. Copy your plugin files to trunk:"
echo "   cd enhanced-autoload-manager-svn"
echo "   cp -r ../enhanced-autoload-manager/* trunk/"
echo ""
echo "3. Add all files to SVN:"
echo "   svn add trunk/* --force"
echo ""
echo "4. Check status:"
echo "   svn status"
echo ""
echo "5. Commit to trunk:"
echo "   svn commit -m 'Initial commit of Enhanced Autoload Manager v1.5.4'"
echo ""
echo "6. Create a tag for version 1.5.4:"
echo "   svn copy trunk tags/1.5.4"
echo "   svn commit -m 'Tagging version 1.5.4'"
echo ""
echo "7. Add plugin assets (optional but recommended):"
echo "   mkdir assets"
echo "   cp ../assets/screenshot-*.png assets/"
echo "   svn add assets/*"
echo "   svn commit -m 'Adding plugin screenshots'"
echo ""
echo "Your plugin will be live at:"
echo "https://wordpress.org/plugins/enhanced-autoload-manager/"
echo ""
echo "Note: It may take up to 72 hours for search results to update."